### ISSUE TITLE
Has this been tested yet?

### ISSUE THREAD

**Issue by imi2003** [SukkoPera/Raemixx500#18]
Hi all

Has this board been tested yet? I have 2 broken A500+ machines that need repair both with confirmed working chipsets, I was looking at another project (A500++) but it seems that the author of that project has not released any sources.
I am willing to order up a few boards and test and report back here.
I live in the UK so i can send you a blank board if they work

regards

Imran

**Comment by SukkoPera** [comment]
Hi,

no, no one has tested the board yet or, if anyone has, they never bothered to report what they found out.

It would be great if you did it, please keep me up to date. :)

**Comment by MBeijer** [comment]
@imi2003 any update? :)

**Comment by imi2003** [comment]
@MBeijer  sorry for the late reply, I'm just waiting for the delivery, since I'm in the UK the package has been delayed because of covid and brexit, it has been with DHL in Germany for the last 3 weeks.

**Comment by Baktus79** [comment]
@imi2003 Did you test the board?

**Comment by zambujal** [comment]
I will test it in 1-2 days and post it here!

**Comment by Calab** [comment]
So, still untested? I have this board and I'm looking to build it but we need a proper BOM.  For example U90-94 are SMT and not part of the A500+ BOM list. Same for the battery holder.

**Comment by kinmami** [comment]
https://hackaday.io/project/180442-rmixx500-amiga-500-mainboard

Fully tested
