### ISSUE TITLE
Missing components in 3D

### ISSUE THREAD

**Issue by AmiManga** [SukkoPera/Raemixx500#19]
I really love attention to detail in this project! This is fantastic. However I noticed that some components are missing in 3D view? For example DB ports, power connector. Am I missing something in my KiCad settings or these files are not included in the project.

**Comment by SukkoPera** [comment]
The 3D model is 100% complete. Some models are included in the `3dModels` directory in the project, others come from [Walter's famous libraries](http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm). You have to download those (there's a git repo at `git://smisioto.eu/kicad_libs.git` as well), save them somewhere and add a `P3D_WALTER` path in KiCad pointing to the `modules/packages3d/walter` in that directory.

**Comment by AmiManga** [comment]
Thank you for your quick reply. I was able to add missing models by following your instructions. Now my motherboard looks fully populated. I must say again, this is cleanest and most complete KiCad project I had a chance to work with so far.

**Comment by SukkoPera** [comment]
Go spread the word then! :)

(Closing, thanks for your interest.)

**Comment by AmiManga** [comment]
I am noticing that after adding P3D_WALTER to the patch I have all 3d elements with exeption DB25F, DB25M, RIGHT_JOY, LEFT_JOY. 

![Raemixx5003d](https://user-images.githubusercontent.com/65513585/103472050-9529c180-4d56-11eb-9a60-27fcbf0db009.png)

Am I missing something? 

Cheers

**Comment by AmiManga** [comment]
Nevermind. Fixed it. I just changed models manually. 

Ranko

**Comment by SukkoPera** [comment]
You are right, I have just realized some paths need to be fixed. Reopening.

**Comment by SukkoPera** [comment]
Please fetch the latest changes and let me know if this is now fixed.
