### ISSUE TITLE
Linked BOM does not identify all components

### ISSUE THREAD

**Issue by Calab** [SukkoPera/Raemixx500#21]
In the wiki, we are told to reference an A500+ bill of material for a parts list. This BOM does not contain all the necessary components to complete this board. U90-94 and the coin battery holder for example. We could really use a proper BOM, or at least a list of differences between the A500+ and this board.

My current issue is: What package sizes are the SMT U90-94?

**Comment by kinmami** [comment]
U90-94 are DT1042-04SO-7	ESD protection. Can be found on Mouser or Digikey

**Comment by Calab** [comment]
U94 is a 74HCT14... Not sure of the package size on this one.

**Comment by Calab** [comment]
I purchased a few different boards from Keith Dumoulin on Facebook.

**Comment by sgerzack** [comment]
I will be using a VBB angus . So the 100nf cap is required I believe ?

**Comment by sgerzack** [comment]
> U94 is a 74HCT14... Not sure of the package size on this one.

I used MM74HCT14MX  Got it from Digikey

**Comment by SukkoPera** [comment]
Then go ask Keith Dumoulin for the BOM and any help you might. He has to provide that since he's the one who got your money. I'm fed up with these people only taking and never giving back to open projects.

**Comment by Calab** [comment]
> Then go ask Keith Dumoulin for the BOM and any help you might need. He has to provide that since he's the one who got your money. I'm fed up with these people only taking and never giving back to open projects. Not to mention that the license for V2 actually even prohibits commercial use so he couldn't sell the board in the first place.

Uhm... he only had the one board and decided that he wasn't going to use it, hence he posted it for sale with some other stuff.

I don't know if he bought it from you originally, or from some other source. I assume from your hostility that you developed the board to make a profit, since that seems to be what has you upset. Myself, I'm just trying to enjoy the Amiga scene. Why else would I spend more money building a machine that it would cost just to buy a whole Amiga 500+?

Personally, I think designing a board, then refusing to provide a proper BOM is just asking for trouble in the first place.

**Comment by SukkoPera** [comment]
Sure, I released ~3 years worth of work under an open license in order to make BIG MONEY! How smart of me! I surely wouldn't have released anything if I had known how dumb the Amiga scene is. All it deserves is things to be shut in drawers and lost forever.

**Comment by Silveriomrs** [comment]
> Sure, I released ~3 years worth of work under an open license in order to make BIG MONEY! How smart of me! I surely wouldn't have released anything if I had known how dumb the Amiga scene is. All it deserves is things to be shut in drawers and lost forever.

Thank you for your work. 
Advice... don't pay a penny for negative comments. Someone who developed something for free and openly have not to give support till the end of his life.

One thing is to understand personal frustration from some users, and other thing is to waste time answering disrespectful comments.

**Comment by Calab** [comment]
> Sure, I released ~3 years worth of work under an open license in order to make BIG MONEY! How smart of me! I surely wouldn't have released anything if I had known how dumb the Amiga scene is. All it deserves is things to be shut in drawers and lost forever.

I apologize for the tone of these postings. I really do appreciated this project and plan to contribute where I can. I had never heard of the project until someone offered me the chance to by his board from him. He's not a commercial producer (that I know of).

I simply opened this issue ticket because I found a shortcoming. I wasn't demanding support or expecting anything to happen right away. The new parts are SMT so should be installed before the through hole components, and I don't know anything about package sizes for SMT parts, so I mentioned them.

I am putting together a proper BOM that can be used by this project, but all I've done is look at the board. I still need to assemble it to find out what is different and what isn't in the linked BOM.

I know you didn't do this to make a profit. I know that it's something that you fit into your spare time. I appreciate that. Please continue to do what you love and share it so others can enjoy it as well.

Take care

**Comment by SukkoPera** [comment]
Thanks for the sympathy @Silveriomrs. I am actually keen on supporting this and all my other projects when it comes to improvement offers or building something new on (part of) them, but much less so when I do the work and selfish others get the money. It frustrates me *a lot* when people cannot tell the good from the bad, and it seems no one from the Amiga "community" can.

@Calab: The A500++ BOM and the notes in the README of this project are all you need to build this board.

**Comment by SukkoPera** [comment]
Oh, I didn't know that. Sadly no-one else has asked for the authorization to sell the board, so I'm afraid your only choice at the moment is to buy 5 from PCBWay and sell the excess ones (I don't care if you do it at cost). Maybe sordan will restock, I don't know, they haven't for me since a long time.

**All** the boards you can find on eBay are from people who are too smart to care for licenses, by the way.

However it ends, thanks for even just bothering to ask, it's a nice gesture to at least **try** to support the original authors :).
